include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - use_super_parameters
    - prefer_relative_imports
    - sort_constructors_first
    - prefer_single_quotes
    - package_api_docs

analyzer:
  exclude:
    - test