name: bluejay
description: A curated collection of useful Flutter and Dart things
version: 0.0.3
author: groovinchip@gmail.com
repository: ''
issue_tracker: ''
homepage: groovinchip.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  http: ^0.13.1

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
