name: bluejay
description: A curated collection of useful Flutter and Dart things
version: 1.0.0+1
repository: https://github.com/GroovinChip/bluejay
issue_tracker: https://github.com/GroovinChip/bluejay/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  http: ^0.13.3

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
