name: bluejay
description: A curated collection of useful Flutter widgets
version: 0.0.3
author: groovinchip@gmail.com
repository: ''
issue_tracker: ''
homepage: groovinchip.dev

environment:
  sdk: ">=2.12.0-179.0.dev <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
